package com.mutiny.moscacal.dao;

import com.mutiny.moscacal.pojo.DefaultModule;
import com.mutiny.moscacal.pojo.DefaultModuleExample;
import java.util.List;

public interface DefaultModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int deleteByPrimaryKey(Integer defaultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int insert(DefaultModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int insertSelective(DefaultModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    List<DefaultModule> selectByExample(DefaultModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    DefaultModule selectByPrimaryKey(Integer defaultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int updateByPrimaryKeySelective(DefaultModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int updateByPrimaryKey(DefaultModule record);
}