package com.mutiny.moscacal.dao;

import com.mutiny.moscacal.pojo.DefaultData;
import com.mutiny.moscacal.pojo.DefaultDataExample;
import java.util.List;

public interface DefaultDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    int deleteByPrimaryKey(Integer defaultmoduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    int insert(DefaultData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    int insertSelective(DefaultData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    List<DefaultData> selectByExample(DefaultDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    DefaultData selectByPrimaryKey(Integer defaultmoduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    int updateByPrimaryKeySelective(DefaultData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-05-02 14:54:42
     */
    int updateByPrimaryKey(DefaultData record);
}