package com.mutiny.moscacal.dao;

import com.mutiny.moscacal.pojo.FileModule;
import com.mutiny.moscacal.pojo.FileModuleExample;
import java.util.List;

public interface FileModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int insert(FileModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int insertSelective(FileModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    List<FileModule> selectByExample(FileModuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    FileModule selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int updateByPrimaryKeySelective(FileModule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int updateByPrimaryKey(FileModule record);
}