package com.mutiny.moscacal.dao;

import com.mutiny.moscacal.pojo.FileAnswer;
import com.mutiny.moscacal.pojo.FileAnswerExample;
import java.util.List;

public interface FileAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    int deleteByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    int insert(FileAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    int insertSelective(FileAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    List<FileAnswer> selectByExample(FileAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    FileAnswer selectByPrimaryKey(Integer fileId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    int updateByPrimaryKeySelective(FileAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-19 17:48:19
     */
    int updateByPrimaryKey(FileAnswer record);
}