package com.mutiny.moscacal.dao;

import com.mutiny.moscacal.pojo.LogCalculate;
import com.mutiny.moscacal.pojo.LogCalculateExample;
import java.util.List;

public interface LogCalculateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int deleteByPrimaryKey(Integer calculateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int insert(LogCalculate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int insertSelective(LogCalculate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    List<LogCalculate> selectByExample(LogCalculateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    LogCalculate selectByPrimaryKey(Integer calculateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int updateByPrimaryKeySelective(LogCalculate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    int updateByPrimaryKey(LogCalculate record);
}