package com.mutiny.moscacal.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table DefaultData
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-17 17:46:15
 */
public class DefaultData implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.DefaultModule_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer defaultmoduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.Default_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer defaultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.Data_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String dataName;

    /**
     * Database Column Remarks:
     *   [是否计算完毕]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.Is_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Boolean isCalculate;

    /**
     * Database Column Remarks:
     *   [是否为有效]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.Is_Userful
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Boolean isUserful;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.Description
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String description;

    /**
     * Database Column Remarks:
     *   [保存的数据]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.File_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DefaultData.KeyFileId
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer keyfileid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.DefaultModule_ID
     *
     * @return the value of DefaultData.DefaultModule_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getDefaultmoduleId() {
        return defaultmoduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.DefaultModule_ID
     *
     * @param defaultmoduleId the value for DefaultData.DefaultModule_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDefaultmoduleId(Integer defaultmoduleId) {
        this.defaultmoduleId = defaultmoduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.Default_ID
     *
     * @return the value of DefaultData.Default_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getDefaultId() {
        return defaultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.Default_ID
     *
     * @param defaultId the value for DefaultData.Default_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDefaultId(Integer defaultId) {
        this.defaultId = defaultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.Data_Name
     *
     * @return the value of DefaultData.Data_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getDataName() {
        return dataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.Data_Name
     *
     * @param dataName the value for DefaultData.Data_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDataName(String dataName) {
        this.dataName = dataName == null ? null : dataName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.Is_Calculate
     *
     * @return the value of DefaultData.Is_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Boolean getIsCalculate() {
        return isCalculate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.Is_Calculate
     *
     * @param isCalculate the value for DefaultData.Is_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setIsCalculate(Boolean isCalculate) {
        this.isCalculate = isCalculate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.Is_Userful
     *
     * @return the value of DefaultData.Is_Userful
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Boolean getIsUserful() {
        return isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.Is_Userful
     *
     * @param isUserful the value for DefaultData.Is_Userful
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setIsUserful(Boolean isUserful) {
        this.isUserful = isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.Description
     *
     * @return the value of DefaultData.Description
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.Description
     *
     * @param description the value for DefaultData.Description
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.File_ID
     *
     * @return the value of DefaultData.File_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.File_ID
     *
     * @param fileId the value for DefaultData.File_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DefaultData.KeyFileId
     *
     * @return the value of DefaultData.KeyFileId
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getKeyfileid() {
        return keyfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DefaultData.KeyFileId
     *
     * @param keyfileid the value for DefaultData.KeyFileId
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setKeyfileid(Integer keyfileid) {
        this.keyfileid = keyfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DefaultData
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", defaultmoduleId=").append(defaultmoduleId);
        sb.append(", defaultId=").append(defaultId);
        sb.append(", dataName=").append(dataName);
        sb.append(", isCalculate=").append(isCalculate);
        sb.append(", isUserful=").append(isUserful);
        sb.append(", description=").append(description);
        sb.append(", fileId=").append(fileId);
        sb.append(", keyfileid=").append(keyfileid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}