package com.mutiny.moscacal.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Default_Module
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-17 17:46:15
 */
public class DefaultModule implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.Default_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer defaultId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.Description
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.Function
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String function;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.Param_Number
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer paramNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.TFunction
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String tfunction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.ChangeFun
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String changefun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Default_Module.multNum
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer multnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.Default_ID
     *
     * @return the value of Default_Module.Default_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getDefaultId() {
        return defaultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.Default_ID
     *
     * @param defaultId the value for Default_Module.Default_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDefaultId(Integer defaultId) {
        this.defaultId = defaultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.Name
     *
     * @return the value of Default_Module.Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.Name
     *
     * @param name the value for Default_Module.Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.Description
     *
     * @return the value of Default_Module.Description
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.Description
     *
     * @param description the value for Default_Module.Description
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.Function
     *
     * @return the value of Default_Module.Function
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getFunction() {
        return function;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.Function
     *
     * @param function the value for Default_Module.Function
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setFunction(String function) {
        this.function = function == null ? null : function.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.Param_Number
     *
     * @return the value of Default_Module.Param_Number
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getParamNumber() {
        return paramNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.Param_Number
     *
     * @param paramNumber the value for Default_Module.Param_Number
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setParamNumber(Integer paramNumber) {
        this.paramNumber = paramNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.TFunction
     *
     * @return the value of Default_Module.TFunction
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getTfunction() {
        return tfunction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.TFunction
     *
     * @param tfunction the value for Default_Module.TFunction
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setTfunction(String tfunction) {
        this.tfunction = tfunction == null ? null : tfunction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.ChangeFun
     *
     * @return the value of Default_Module.ChangeFun
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getChangefun() {
        return changefun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.ChangeFun
     *
     * @param changefun the value for Default_Module.ChangeFun
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setChangefun(String changefun) {
        this.changefun = changefun == null ? null : changefun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Default_Module.multNum
     *
     * @return the value of Default_Module.multNum
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getMultnum() {
        return multnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Default_Module.multNum
     *
     * @param multnum the value for Default_Module.multNum
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setMultnum(Integer multnum) {
        this.multnum = multnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Default_Module
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", defaultId=").append(defaultId);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", function=").append(function);
        sb.append(", paramNumber=").append(paramNumber);
        sb.append(", tfunction=").append(tfunction);
        sb.append(", changefun=").append(changefun);
        sb.append(", multnum=").append(multnum);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}