package com.mutiny.moscacal.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table File_Answer
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-17 17:46:15
 */
public class FileAnswer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.File_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.File_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.Module_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.File_URL
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.Encode_Algorithm
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String encodeAlgorithm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.PublicKey
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String publickey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column File_Answer.PrivateKey
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String privatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.File_ID
     *
     * @return the value of File_Answer.File_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.File_ID
     *
     * @param fileId the value for File_Answer.File_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.File_Name
     *
     * @return the value of File_Answer.File_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.File_Name
     *
     * @param fileName the value for File_Answer.File_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.Module_ID
     *
     * @return the value of File_Answer.Module_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.Module_ID
     *
     * @param moduleId the value for File_Answer.Module_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.File_URL
     *
     * @return the value of File_Answer.File_URL
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.File_URL
     *
     * @param fileUrl the value for File_Answer.File_URL
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.Encode_Algorithm
     *
     * @return the value of File_Answer.Encode_Algorithm
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getEncodeAlgorithm() {
        return encodeAlgorithm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.Encode_Algorithm
     *
     * @param encodeAlgorithm the value for File_Answer.Encode_Algorithm
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setEncodeAlgorithm(String encodeAlgorithm) {
        this.encodeAlgorithm = encodeAlgorithm == null ? null : encodeAlgorithm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.PublicKey
     *
     * @return the value of File_Answer.PublicKey
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getPublickey() {
        return publickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.PublicKey
     *
     * @param publickey the value for File_Answer.PublicKey
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setPublickey(String publickey) {
        this.publickey = publickey == null ? null : publickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column File_Answer.PrivateKey
     *
     * @return the value of File_Answer.PrivateKey
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getPrivatekey() {
        return privatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column File_Answer.PrivateKey
     *
     * @param privatekey the value for File_Answer.PrivateKey
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setPrivatekey(String privatekey) {
        this.privatekey = privatekey == null ? null : privatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table File_Answer
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", fileName=").append(fileName);
        sb.append(", moduleId=").append(moduleId);
        sb.append(", fileUrl=").append(fileUrl);
        sb.append(", encodeAlgorithm=").append(encodeAlgorithm);
        sb.append(", publickey=").append(publickey);
        sb.append(", privatekey=").append(privatekey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}