package com.mutiny.moscacal.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table KeyFile
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-17 17:46:15
 */
public class KeyFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KeyFile.KeyFileID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer keyfileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KeyFile.FileURL
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String fileurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KeyFile
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KeyFile.KeyFileID
     *
     * @return the value of KeyFile.KeyFileID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getKeyfileid() {
        return keyfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KeyFile.KeyFileID
     *
     * @param keyfileid the value for KeyFile.KeyFileID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setKeyfileid(Integer keyfileid) {
        this.keyfileid = keyfileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KeyFile.FileURL
     *
     * @return the value of KeyFile.FileURL
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getFileurl() {
        return fileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KeyFile.FileURL
     *
     * @param fileurl the value for KeyFile.FileURL
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setFileurl(String fileurl) {
        this.fileurl = fileurl == null ? null : fileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KeyFile
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keyfileid=").append(keyfileid);
        sb.append(", fileurl=").append(fileurl);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}