package com.mutiny.moscacal.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Log
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-17 17:46:15
 */
public class Log implements Serializable {
    /**
     * Database Column Remarks:
     *   操作ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Log_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer logId;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.User_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   操作名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Operation_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String operationName;

    /**
     * Database Column Remarks:
     *   调用函数名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Method
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String method;

    /**
     * Database Column Remarks:
     *   函数参数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Params
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String params;

    /**
     * Database Column Remarks:
     *   影响的表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Database_Influence
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String databaseInfluence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.Operation_Time
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Date operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log.IP
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Log
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Log_ID
     *
     * @return the value of Log.Log_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Log_ID
     *
     * @param logId the value for Log.Log_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.User_ID
     *
     * @return the value of Log.User_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.User_ID
     *
     * @param userId the value for Log.User_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Operation_Name
     *
     * @return the value of Log.Operation_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getOperationName() {
        return operationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Operation_Name
     *
     * @param operationName the value for Log.Operation_Name
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setOperationName(String operationName) {
        this.operationName = operationName == null ? null : operationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Method
     *
     * @return the value of Log.Method
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Method
     *
     * @param method the value for Log.Method
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Params
     *
     * @return the value of Log.Params
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Params
     *
     * @param params the value for Log.Params
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Database_Influence
     *
     * @return the value of Log.Database_Influence
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getDatabaseInfluence() {
        return databaseInfluence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Database_Influence
     *
     * @param databaseInfluence the value for Log.Database_Influence
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setDatabaseInfluence(String databaseInfluence) {
        this.databaseInfluence = databaseInfluence == null ? null : databaseInfluence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.Operation_Time
     *
     * @return the value of Log.Operation_Time
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.Operation_Time
     *
     * @param operationTime the value for Log.Operation_Time
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log.IP
     *
     * @return the value of Log.IP
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log.IP
     *
     * @param ip the value for Log.IP
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", userId=").append(userId);
        sb.append(", operationName=").append(operationName);
        sb.append(", method=").append(method);
        sb.append(", params=").append(params);
        sb.append(", databaseInfluence=").append(databaseInfluence);
        sb.append(", operationTime=").append(operationTime);
        sb.append(", ip=").append(ip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}