package com.mutiny.moscacal.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Log_Calculate
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-17 17:46:15
 */
public class LogCalculate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.Calculate_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer calculateId;

    /**
     * Database Column Remarks:
     *   操作ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.User_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   固定模型为数据源ID，自定义模型为模型ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.ModuleID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Integer moduleid;

    /**
     * Database Column Remarks:
     *   计算/查看结果
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.Type
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.Operation_Time
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Date operationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.IP
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Log_Calculate.Is_default
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private Boolean isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.Calculate_ID
     *
     * @return the value of Log_Calculate.Calculate_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getCalculateId() {
        return calculateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.Calculate_ID
     *
     * @param calculateId the value for Log_Calculate.Calculate_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setCalculateId(Integer calculateId) {
        this.calculateId = calculateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.User_ID
     *
     * @return the value of Log_Calculate.User_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.User_ID
     *
     * @param userId the value for Log_Calculate.User_ID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.ModuleID
     *
     * @return the value of Log_Calculate.ModuleID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Integer getModuleid() {
        return moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.ModuleID
     *
     * @param moduleid the value for Log_Calculate.ModuleID
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setModuleid(Integer moduleid) {
        this.moduleid = moduleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.Type
     *
     * @return the value of Log_Calculate.Type
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.Type
     *
     * @param type the value for Log_Calculate.Type
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.Operation_Time
     *
     * @return the value of Log_Calculate.Operation_Time
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Date getOperationTime() {
        return operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.Operation_Time
     *
     * @param operationTime the value for Log_Calculate.Operation_Time
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setOperationTime(Date operationTime) {
        this.operationTime = operationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.IP
     *
     * @return the value of Log_Calculate.IP
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.IP
     *
     * @param ip the value for Log_Calculate.IP
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Log_Calculate.Is_default
     *
     * @return the value of Log_Calculate.Is_default
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Log_Calculate.Is_default
     *
     * @param isDefault the value for Log_Calculate.Is_default
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Log_Calculate
     *
     * @mbg.generated 2020-03-17 17:46:15
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", calculateId=").append(calculateId);
        sb.append(", userId=").append(userId);
        sb.append(", moduleid=").append(moduleid);
        sb.append(", type=").append(type);
        sb.append(", operationTime=").append(operationTime);
        sb.append(", ip=").append(ip);
        sb.append(", isDefault=").append(isDefault);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}