package com.mutiny.moscacal.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table User
 *
 * @mbg.generated do_not_delete_during_merge 2020-03-20 16:59:44
 */
public class User implements Serializable {
    /**
     * Database Column Remarks:
     *   账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.ID
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private String id;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Password
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private String password;

    /**
     * Database Column Remarks:
     *   头像URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Portrait_ID
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private Integer portraitId;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Name
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private String name;

    /**
     * Database Column Remarks:
     *   电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Tel
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private String tel;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Email
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private String email;

    /**
     * Database Column Remarks:
     *   身份标签[政府|企业管理员|企业职员]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Type
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private String type;

    /**
     * Database Column Remarks:
     *   是否被删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Is_Userful
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private Boolean isUserful;

    /**
     * Database Column Remarks:
     *   是否通过验证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.Is_Pass
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private Boolean isPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.GovernId
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private Integer governid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CompanyId
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private Integer companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.CreatTime
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table User
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.ID
     *
     * @return the value of User.ID
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.ID
     *
     * @param id the value for User.ID
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Password
     *
     * @return the value of User.Password
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Password
     *
     * @param password the value for User.Password
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Portrait_ID
     *
     * @return the value of User.Portrait_ID
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public Integer getPortraitId() {
        return portraitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Portrait_ID
     *
     * @param portraitId the value for User.Portrait_ID
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setPortraitId(Integer portraitId) {
        this.portraitId = portraitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Name
     *
     * @return the value of User.Name
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Name
     *
     * @param name the value for User.Name
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Tel
     *
     * @return the value of User.Tel
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Tel
     *
     * @param tel the value for User.Tel
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Email
     *
     * @return the value of User.Email
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Email
     *
     * @param email the value for User.Email
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Type
     *
     * @return the value of User.Type
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Type
     *
     * @param type the value for User.Type
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Is_Userful
     *
     * @return the value of User.Is_Userful
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public Boolean getIsUserful() {
        return isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Is_Userful
     *
     * @param isUserful the value for User.Is_Userful
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setIsUserful(Boolean isUserful) {
        this.isUserful = isUserful;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.Is_Pass
     *
     * @return the value of User.Is_Pass
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public Boolean getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.Is_Pass
     *
     * @param isPass the value for User.Is_Pass
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setIsPass(Boolean isPass) {
        this.isPass = isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.GovernId
     *
     * @return the value of User.GovernId
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public Integer getGovernid() {
        return governid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.GovernId
     *
     * @param governid the value for User.GovernId
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setGovernid(Integer governid) {
        this.governid = governid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CompanyId
     *
     * @return the value of User.CompanyId
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CompanyId
     *
     * @param companyid the value for User.CompanyId
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.CreatTime
     *
     * @return the value of User.CreatTime
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.CreatTime
     *
     * @param creattime the value for User.CreatTime
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbg.generated 2020-03-20 16:59:44
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", password=").append(password);
        sb.append(", portraitId=").append(portraitId);
        sb.append(", name=").append(name);
        sb.append(", tel=").append(tel);
        sb.append(", email=").append(email);
        sb.append(", type=").append(type);
        sb.append(", isUserful=").append(isUserful);
        sb.append(", isPass=").append(isPass);
        sb.append(", governid=").append(governid);
        sb.append(", companyid=").append(companyid);
        sb.append(", creattime=").append(creattime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}